/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pandemieprojet;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class admin3 extends javax.swing.JFrame {
DefaultTableModel modelo;
    /**
     * Creates new form admin3
     * @throws java.lang.ClassNotFoundException
     */
    public admin3() throws ClassNotFoundException, SQLException {
        initComponents();
        showTabledata();
    }
void showTabledata() throws ClassNotFoundException, SQLException{
    
    connection con;
       String [] t2={"id","gouvernement","cas","deces","retabli","test du jour","date"};
       
            String [] t=new String[7];
            modelo =new DefaultTableModel(null,t2); 
            
            
            con = new connection();
            Statement cmd = con.c.createStatement();
             ResultSet res = cmd.executeQuery("SELECT idt,gouvernement,nbcas,nbrDT,nbrREC,nbrTESTJ,datecas FROM tunisie ORDER BY idt;");
             while(res.next()){
             
             t[0]= res.getString("idt");
             t[1]= res.getString("gouvernement");
             t[2]= res.getString("nbcas");
              t[3]= res.getString("nbrDT");
              t[4]= res.getString("nbrREC");
              t[5]= res.getString("nbrTESTJ");
              t[6]= res.getString("datecas");
              
              
              
              
             
             modelo.addRow(t);}
             tt.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tt = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        comboA = new javax.swing.JComboBox<String>();
        decesA = new javax.swing.JTextField();
        casA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        retabA = new javax.swing.JTextField();
        testA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        yyyy = new javax.swing.JTextField();
        mm = new javax.swing.JTextField();
        dd = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        yy = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        casM = new javax.swing.JTextField();
        decesM = new javax.swing.JTextField();
        retabM = new javax.swing.JTextField();
        testM = new javax.swing.JTextField();
        comboM = new javax.swing.JComboBox();
        yyyyM = new javax.swing.JTextField();
        mmM = new javax.swing.JTextField();
        ddM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        sup = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        tt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(tt);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ariana", "Beja", "Ben arous", "bizerte", "Gabes", "Gafsa", "Jendouba", "Kairouen", "kasserine", "kebilli", "Le Kef", "Mahdia", "Mannouba", "Medenine", "Monastir", "Nabeul", "Sfax", "Sidi bouzid", "Siliana", "Sousse", "Tataouine", "Tozeur", "Tunis", "Zaghouan" }));
        comboA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboAMouseClicked(evt);
            }
        });
        comboA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAActionPerformed(evt);
            }
        });

        jLabel4.setText("Date:");

        jLabel5.setText("Gouvernement:");

        retabA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retabAActionPerformed(evt);
            }
        });

        testA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testAActionPerformed(evt);
            }
        });

        jLabel7.setText("Nouveaux cas:");

        jLabel8.setText("Nouveaux décés:");

        jLabel9.setText("Retablis:");

        jLabel11.setText("Test du jour:");

        mm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmActionPerformed(evt);
            }
        });

        dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddActionPerformed(evt);
            }
        });

        jLabel18.setText("-");

        jLabel19.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboA, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casA, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(retabA, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(decesA, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(testA, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(yyyy, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addGap(7, 7, 7)
                        .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yyyy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decesA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retabA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(testA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setText("Ajouter");

        yy.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("ID de la ligne à modifier:");

        jLabel10.setText("Pays :");

        jLabel12.setText("Date :");

        jLabel13.setText("Nouveaux cas :");

        jLabel14.setText("Nouveaux décés :");

        jLabel15.setText("Retablis :");

        jLabel16.setText("Test du jour :");

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        casM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casMActionPerformed(evt);
            }
        });

        comboM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ariana", "Beja", "Ben arous", "bizerte", "Gabes", "Gafsa", "Jendouba", "Kairouen", "kasserine", "kebilli", "Le Kef", "Mahdia", "Mannouba", "Medenine", "Monastir", "Nabeul", "Sfax", "Sidi bouzid", "Siliana", "Sousse", "Tataouine", "Tozeur", "Tunis", "Zaghouan" }));

        mmM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout yyLayout = new javax.swing.GroupLayout(yy);
        yy.setLayout(yyLayout);
        yyLayout.setHorizontalGroup(
            yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yyLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(yyLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(yyyyM, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mmM, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ddM, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yyLayout.createSequentialGroup()
                        .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(yyLayout.createSequentialGroup()
                                .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                        .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(yyLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idM, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(yyLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(decesM, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(retabM, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(testM, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(yyLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(casM, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))))
            .addGroup(yyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        yyLayout.setVerticalGroup(
            yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(yyLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mmM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ddM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yyLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(yyyyM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(decesM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(retabM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(7, 7, 7)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setText("Modifier");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setText("ID ligne à supprimer :");

        sup.setToolTipText("");

        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(sup, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(sup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("Supprimer");

        button1.setLabel("Retour");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jButton4.setText("Actualiser");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(yy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
connection con = null;
Statement cmd = null;
 ResultSet res = null;
 
    try {
        con = new connection();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    try {
        cmd = con.c.createStatement();
    } catch (SQLException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        res = cmd.executeQuery("SELECT idt FROM tunisie;");
    } catch (SQLException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
        int a1 = 0;
    try {
        while (res.next()){
            a1=res.getInt("idt");
        }
    } catch (SQLException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
             int last=a1+1;
             System.out.print(last);
             String a = null;
             int x =comboA.getSelectedIndex();
            
             switch (x){
                case 0:a="ariena";break;
                case 1:a="beja";break;
                case 2:a="benarous";break;
                case 3:a="bizerte";break;
                case 4:a="gabes";break;
                case 5:a="gafsa";break;
                case 6:a="jendouba";break;
                case 7:a="kairaouen";break;
                case 8:a="kasserine";break;
                case 9:a="kebili";break;
                case 10:a="kef";break;
                case 11:a="mahdia";break;
                case 12:a="mannouba";break;
                case 13:a="mednine";break;
                case 14:a="monastir";break;
                case 15:a="nabeul";break;
                case 16:a="sfax";break;
                case 17:a="sisibouzid";break;
                case 18:a="siliana";break;
                case 19:a="sousse";break;
                case 20:a="tataouine";break;
                case 21:a="tozeur";break;
                case 22:a="tunis";break;
                case 23:a="zaghouan";break;
        
        }
String a2=a.toUpperCase();
System.out.println(a2);
    Statement cmd2=null;
     
try{
        cmd2 = con.c.createStatement();
    } catch (SQLException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
ResultSet res2=null;
int tot=0;
System.out.println(tot);
    try {
        res2=cmd2.executeQuery("SELECT MAX(nbrTEST) FROM tunisie where gouvernement='"+a2+"';");
        
        while (res2.next()){
            tot=res2.getInt("MAX(nbrTEST)");
            
        }
    } catch (SQLException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
 System.out.println("finale"+tot);
 int tes =Integer.parseInt(testA.getText());
 tot=tot+tes;
 System.out.println("finale2  "+tot);

 
 String year=String.valueOf(yyyy.getText());
 int month=Integer.parseInt(mm.getText());
 int day=Integer.parseInt(dd.getText());
 String dateaj=year+"-"+Integer.toString(month)+"-"+Integer.toString(day);
 System.out.println(dateaj);
 
/*String dateaj2 =String.valueOf(dateA.getText());
String dateaj=dateaj2.toString();

System.out.println("date  "+dateaj);*/
             int nvcas =Integer.parseInt(casA.getText());
             int nvdeces=Integer.parseInt(decesA.getText());
             int retab =Integer.parseInt(retabA.getText());
              System.out.println("nvc"+nvdeces);
              System.out.println("retab"+retab);
              
              
             
             
String ss=("INSERT INTO tunisie VALUES ('"+last+"','"+a2+"','"+nvcas+"','"+nvdeces+"','"+retab+"','"+tot+"','"+tes+"','"+dateaj+"');");
             
    try {
        cmd2.executeUpdate(ss);
    } catch (SQLException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
             
     javax.swing.JOptionPane.showMessageDialog(null,"ajoutée");
     yyyy.setText(""); mm.setText("");dd.setText("");
     testA.setText("");
     retabA.setText("");
     casA.setText("");
     decesA.setText("");
     
     
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboAMouseClicked
        // TODO add your handling code here:
        try{    connection  con;
           
                con = new connection();
                 Statement cmd = con.c.createStatement();
            ResultSet res = cmd.executeQuery("SELECT gouvernement FROM tunisie;");
while (res.next())
{            int i=1;
boolean found = false;
while(i<(comboA.getItemCount())&& !found){
              System.out.println(comboA.getItemAt(i));
            System.out.println(res.getString("gouvernement"));
    if(comboA.getItemAt(i).equals(res.getString("gouvernement"))){
        found = true;
    comboA.removeItemAt(i);
    }
    else i++;}
}
            }
           
         catch (SQLException ex) {
         System.out.println("fail");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboAMouseClicked

    private void retabAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retabAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retabAActionPerformed

    private void testAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testAActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
connection con = null;
Statement cmd = null;
 ResultSet res = null;
 
    try {
        con = new connection();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    try {
        cmd = con.c.createStatement();
    } catch (SQLException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    int id=Integer.parseInt(idM.getText());
    String a = null;
             int x =comboM.getSelectedIndex();
            
             switch (x){
                case 0:a="ariena";break;
                case 1:a="beja";break;
                case 2:a="benarous";break;
                case 3:a="bizerte";break;
                case 4:a="gabes";break;
                case 5:a="gafsa";break;
                case 6:a="jendouba";break;
                case 7:a="kairaouen";break;
                case 8:a="kasserine";break;
                case 9:a="kebili";break;
                case 10:a="kef";break;
                case 11:a="mahdia";break;
                case 12:a="mannouba";break;
                case 13:a="mednine";break;
                case 14:a="monastir";break;
                case 15:a="nabeul";break;
                case 16:a="sfax";break;
                case 17:a="sisibouzid";break;
                case 18:a="siliana";break;
                case 19:a="sousse";break;
                case 20:a="tataouine";break;
                case 21:a="tozeur";break;
                case 22:a="tunis";break;
                case 23:a="zaghouan";break;
        
        }
String a2=a.toUpperCase();
    String year=String.valueOf(yyyyM.getText());
 int month=Integer.parseInt(mmM.getText());
 int day=Integer.parseInt(ddM.getText());
 String dateaj=year+"-"+Integer.toString(month)+"-"+Integer.toString(day);
 int nvcas =Integer.parseInt(casM.getText());
             int nvdeces=Integer.parseInt(decesM.getText());
             int retab =Integer.parseInt(retabM.getText());
             
    int tot=0;
System.out.println(tot);
    try {
        res=cmd.executeQuery("SELECT MAX(nbrTEST) FROM tunisie where gouvernement='"+a2+"' and datecas <'"+dateaj+"' ;");
        
        while (res.next()){
            tot=res.getInt("MAX(nbrTEST)");
            
        }
    } catch (SQLException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
 System.out.println("finale"+tot);
 int tes =Integer.parseInt(testM.getText());
 tot=tot+tes;
  
    String ss=("UPDATE tunisie SET idt='"+id+"',gouvernement='"+a2+"',nbcas='"+nvcas+"',nbrDT='"+nvdeces+"',nbrREC='"+retab+"',nbrTEST='"+tot+"',nbrTESTJ='"+tes+"',datecas='"+dateaj+"' where idt='"+id+"' ;");
             
    try {
        cmd.executeUpdate(ss);
    } catch (SQLException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
             yyyyM.setText(""); mmM.setText("");ddM.setText("");
     testM.setText("");
     retabM.setText("");
     casM.setText("");
     decesM.setText("");
     javax.swing.JOptionPane.showMessageDialog(null,"modifié");
    
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
connection con = null;
    try {
        con = new connection();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        Statement cmd = con.c.createStatement();
        int x=Integer.parseInt(sup.getText());
        String ss=("DELETE FROM tunisie where idt='"+x+"' ;");
        sup.setText("");
            javax.swing.JOptionPane.showMessageDialog(null,"la ligne a été supprimée");
            cmd.executeUpdate(ss);
        // TODO add your handling code here:
    } catch (SQLException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void casMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casMActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
admin2 t = new admin2();
            t.setVisible(true);
            this.hide();
// TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void mmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmActionPerformed

    private void ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddActionPerformed

    private void mmMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmMActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
DefaultTableModel modelo;
connection con = null;
       String [] t2={"id","gouvernement","cas","deces","retabli","test du jour","date"};
       
            String [] t=new String[7];
            modelo =new DefaultTableModel(null,t2); 
            
            
    try {
        con = new connection();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
            Statement cmd = null;
    try {
        cmd = con.c.createStatement();
    } catch (SQLException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
             ResultSet res = null;
    try {
        res = cmd.executeQuery("SELECT idt,gouvernement,nbcas,nbrDT,nbrREC,nbrTESTJ,datecas FROM tunisie ORDER BY idt;");
    } catch (SQLException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        while(res.next()){
            
            try {
                t[0]= res.getString("idt");
            } catch (SQLException ex) {
                Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
            }
            t[1]= res.getString("gouvernement");
            t[2]= res.getString("nbcas");
            t[3]= res.getString("nbrDT");
            t[4]= res.getString("nbrREC");
            t[5]= res.getString("nbrTESTJ");
            t[6]= res.getString("datecas");
            
            
            
            
            
            modelo.addRow(t);}
    } catch (SQLException ex) {
        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
    }
             tt.setModel(modelo);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(admin3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(admin3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(admin3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(admin3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    try {
                        new admin3().setVisible(true);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(admin3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
          
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JTextField casA;
    private javax.swing.JTextField casM;
    private javax.swing.JComboBox<String> comboA;
    private javax.swing.JComboBox comboM;
    private javax.swing.JTextField dd;
    private javax.swing.JTextField ddM;
    private javax.swing.JTextField decesA;
    private javax.swing.JTextField decesM;
    private javax.swing.JTextField idM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mm;
    private javax.swing.JTextField mmM;
    private javax.swing.JTextField retabA;
    private javax.swing.JTextField retabM;
    private javax.swing.JTextField sup;
    private javax.swing.JTextField testA;
    private javax.swing.JTextField testM;
    private javax.swing.JTable tt;
    private javax.swing.JPanel yy;
    private javax.swing.JTextField yyyy;
    private javax.swing.JTextField yyyyM;
    // End of variables declaration//GEN-END:variables
}
