/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pandemieprojet;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;

/**
 *
 * @author asus
 */
public class cascontam extends javax.swing.JFrame {
DefaultTableModel modelo;
    /**
     * Creates new form cascontam
     */
    public cascontam() throws ClassNotFoundException, SQLException {
        initComponents();
        showDate();
        showTime();
        showwcase();
        showDeath();
        showREC();
        showTEST();
        showTabledata();
        
    }
    void showTEST() throws ClassNotFoundException, SQLException{
    connection con;
       
            con = new connection();
            Statement cmd = con.c.createStatement();
             ResultSet res = cmd.executeQuery("SELECT SUM(nbrTEST) FROM tunisie ;");
             /*int columnCount = res.getMetaData().getColumnCount();
 System.out.println("column count : "+columnCount);*/
            
              while(res.next())
        {       String count = res.getString("SUM(nbrTEST)");
           
        test.setText(count);}
              
          
             
             con.c.close();
    
    
    }
void showTabledata() throws ClassNotFoundException, SQLException{
    DefaultTableModel modelo;
    connection con;
       String [] t2={"pays","cas","deces","retabli"};
       
            String [] t=new String[4];
            modelo =new DefaultTableModel(null,t2); 
            
            
            con = new connection();
            Statement cmd = con.c.createStatement();
             ResultSet res = cmd.executeQuery("SELECT gouvernement,SUM(nbcas),SUM(nbrDT),SUM(nbrREC)FROM tunisie GROUP BY gouvernement;");
             while(res.next()){ t[0]= res.getString("gouvernement");
             t[1]= res.getString("SUM(nbcas)");
             t[2]= res.getString("SUM(nbrDT)");
             t[3]= res.getString("SUM(nbrREC)");
             modelo.addRow(t);}
             tabtun.setModel(modelo);
    }
void showwcase() throws ClassNotFoundException, SQLException{
     connection con;
       
            con = new connection();
            Statement cmd = con.c.createStatement();
             ResultSet res = cmd.executeQuery("SELECT SUM(nbcas) FROM tunisie ;");
             /*int columnCount = res.getMetaData().getColumnCount();
 System.out.println("column count : "+columnCount);*/
            
              while(res.next())
        {       String count = res.getString("SUM(nbcas)");
           
        caspos.setText(count);}
              
          
             
             con.c.close();
}
void showDeath() throws ClassNotFoundException, SQLException{
     connection con;
       
            con = new connection();
            Statement cmd = con.c.createStatement();
             ResultSet res = cmd.executeQuery("SELECT SUM(nbrDT) FROM tunisie ;");
             /*int columnCount = res.getMetaData().getColumnCount();
 System.out.println("column count : "+columnCount);*/
            
              while(res.next())
        {       String count = res.getString("SUM(nbrDT)");
           
        deces.setText(count);}
              
          
             
             con.c.close();
}
void showREC() throws ClassNotFoundException, SQLException{
     connection con;
       
            con = new connection();
            Statement cmd = con.c.createStatement();
             ResultSet res = cmd.executeQuery("SELECT SUM(nbrREC) FROM tunisie ;");
             /*int columnCount = res.getMetaData().getColumnCount();
 System.out.println("column count : "+columnCount);*/
            
              while(res.next())
        {       String count = res.getString("SUM(nbrREC)");
           
        retab.setText(count);}
              
          
             
             con.c.close();
}

void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-YYYY");
        date.setText(s.format(d));
    }    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

 void showTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                 Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
        time.setText(s.format(d));
            }

        }
        ).start();
    }@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        datee = new javax.swing.JTextField();
        gou = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        retab = new javax.swing.JLabel();
        deces = new javax.swing.JLabel();
        caspos = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabtun = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        test = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setText("Total cas positives : ");

        jLabel2.setText("Total décès:");

        jLabel3.setText("Total cas retablis :");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Date:");

        jLabel6.setText("Gouvernerat:");

        datee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateeActionPerformed(evt);
            }
        });

        gou.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tout", "Ariana/أريانة", "Beja/ باجة", "Ben arous/بن عروس", "bizerte/بنزرت", "Gabes/قابس", "Gafsa/قفصة", "Jendouba/جندوبة", "Kairouen/القيروان", "kasserine/القصرين", "kebilli/قبلي", "Le Kef/الكاف", "Mahdia/المهدية", "Mannouba/منوبة", "Medenine/مدنين", "Monastir/المنستير", "Nabeul/نابل", "Sfax/صفاقس", "Sidi bouzid/سيدي بوزيد", "Siliana/سليانة", "Sousse/سوسة", "Tataouine/تطاوين", "Tozeur/توزر", "Tunis/تونس", "Zaghouan/زغوان" }));
        gou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gouActionPerformed(evt);
            }
        });

        jButton2.setText("Rechercher ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("oblig*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(datee, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gou, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jButton2))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(datee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(gou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        time.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        time.setText("heure");

        retab.setText("a");

        deces.setText("b");

        caspos.setText("c");

        date.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        date.setText("date");

        jButton3.setText("Voir details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tabtun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Gouvernement", "Cas", "Deces", "Retabli"
            }
        ));
        jScrollPane1.setViewportView(tabtun);

        jLabel7.setText("Total test :");

        test.setText("k");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(caspos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(deces)
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(retab)
                                .addGap(119, 119, 119))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(test)
                                .addGap(117, 117, 117))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(caspos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deces)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(retab)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(test)))
                .addGap(11, 11, 11)
                .addComponent(jButton3)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(time)
                    .addComponent(jButton1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
SuivieTun ac =new SuivieTun();
        ac.setVisible(true);
        this.hide();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dateeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
DefaultTableModel modelo;
    connection con = null;
       String [] t2={"pays","cas","deces","retabli"};
       
            String [] t=new String[4];
            modelo =new DefaultTableModel(null,t2); 
            
            
    try {
        con = new connection();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(cascontam.class.getName()).log(Level.SEVERE, null, ex);
    }
            Statement cmd = null;
    try {
        cmd = con.c.createStatement();
    } catch (SQLException ex) {
        Logger.getLogger(cascontam.class.getName()).log(Level.SEVERE, null, ex);
    }
             ResultSet res = null;
    try {
        res = cmd.executeQuery("SELECT gouvernement,SUM(nbcas),SUM(nbrDT),SUM(nbrREC) FROM tunisie GROUP BY gouvernement;");
    } catch (SQLException ex) {
        Logger.getLogger(cascontam.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        while(res.next()){ t[0]= res.getString("gouvernement");
        try {
            t[1]= res.getString("SUM(nbcas)");
        } catch (SQLException ex) {
            Logger.getLogger(cascontam.class.getName()).log(Level.SEVERE, null, ex);
        }
        t[2]= res.getString("SUM(nbrDT)");
        t[3]= res.getString("SUM(nbrREC)");
        modelo.addRow(t);}
    } catch (SQLException ex) {
        Logger.getLogger(cascontam.class.getName()).log(Level.SEVERE, null, ex);
    }
             tabtun.setModel(modelo);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String a = null;
int x=gou.getSelectedIndex();
switch (x){
    case 0:a="tout"; break;
        case 1:a="ariena";break;
            case 2:a="beja";break;
                case 3:a="benarous";break;
                case 4:a="bizerte";break;
                case 5:a="gabes";break;
                case 6:a="gafsa";break;
                case 7:a="jendouba";break;
                case 8:a="kairaouen";break;
                    case 9:a="kasserine";break;
                        case 10:a="kebili";break;
                case 11:a="kef";break;
                case 12:a="mahdia";break;
                case 13:a="mannouba";break;
                case 14:a="mednine";break;
                case 15:a="monastir";break;
                case 16:a="nabeul";break;
                case 17:a="sfax";break;
                case 18:a="sisibouzid";break;
                case 19:a="siliana";break;
                case 20:a="sousse";break;
                case 21:a="tataouine";break;
                case 22:a="tozeur";break;
                case 23:a="tunis";break;
                case 24:a="zaghouan";break;
        
        

}
connection con = null ;
        String [] t2={"pays","cas","deces","retabli"};
       
            String [] t=new String[4];
            modelo =new DefaultTableModel(null,t2); 
            String p=toUpperCase(a);
            System.out.print(p);
            String d=datee.getText();
            System.out.print(d);
            
    try {
        con = new connection();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(SuivieWorld.class.getName()).log(Level.SEVERE, null, ex);
    }
            Statement cmd = null;
    try {
        cmd = con.c.createStatement();
    } catch (SQLException ex) {
        Logger.getLogger(SuivieWorld.class.getName()).log(Level.SEVERE, null, ex);
    }
             ResultSet res = null;
    try {
        if(p.equals("TOUT")) {
             System.out.print(p);
        res = cmd.executeQuery("SELECT gouvernement,nbcas,nbrDT,nbrREC FROM tunisie where datecas='"+d+"';");}
        else {
                res = cmd.executeQuery("SELECT gouvernement,nbcas,nbrDT,nbrREC FROM tunisie where gouvernement='"+p+"' and datecas='"+d+"' ;");}
    } catch (SQLException ex) {
        Logger.getLogger(SuivieWorld.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        while(res.next()){ t[0]= res.getString("gouvernement");
        t[1]= res.getString("nbcas");
        t[2]= res.getString("nbrDT");
        t[3]= res.getString("nbrREC");
        modelo.addRow(t);}
    } catch (SQLException ex) {
        Logger.getLogger(SuivieWorld.class.getName()).log(Level.SEVERE, null, ex);
    }
             tabtun.setModel(modelo);




    }//GEN-LAST:event_jButton2ActionPerformed

    private void gouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gouActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cascontam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cascontam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cascontam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cascontam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new cascontam().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(cascontam.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(cascontam.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caspos;
    private javax.swing.JLabel date;
    private javax.swing.JTextField datee;
    private javax.swing.JLabel deces;
    private javax.swing.JComboBox gou;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel retab;
    private javax.swing.JTable tabtun;
    private javax.swing.JLabel test;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
