/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pandemieprojet;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;

/**
 *
 * @author asus
 */
public class hopital extends javax.swing.JFrame {

    /**
     * Creates new form hopital
     */
    public hopital() {
        initComponents();

    showDate();
        showTime();}
void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-YYYY");
        date.setText(s.format(d));
    }
void showTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                 Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
        time.setText(s.format(d));
            }

        }
        ).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ho = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        th = new javax.swing.JTable();
        equ = new javax.swing.JButton();
        fou = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setText("Rechrcher: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("l’état général des hôpitaux");

        ho.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tous les Hôpitaux", "Hôpital militaire", "Hôpital CHARLES NICOLLE", "Hôpital La RABTA", "Centre de traumatologie et des grands brûlés à Ben Arous", "Hôpital Mongi Slim La Marsa ", "Hôpital d’enfant", "Hôpital SALAH AZAIEZ ", "Hôpital Mahmoud el Matri ARIANA ", "Hôpital Wassila Bourguiba", "Institut El Kassab" }));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        time.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        time.setText("heure");

        date.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        date.setText("date");

        jButton2.setText("Retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        th.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Hopital", "Cas hospitalisé", " Lits encore disponibles en réa"
            }
        ));
        jScrollPane1.setViewportView(th);

        equ.setText("Equipements manquants");
        equ.setEnabled(false);
        equ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equActionPerformed(evt);
            }
        });

        fou.setText("Demande Fournitures");
        fou.setEnabled(false);
        fou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fouActionPerformed(evt);
            }
        });

        jButton5.setText("Appels à dons");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(45, 45, 45)
                                        .addComponent(ho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(65, 65, 65)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(equ)
                .addGap(51, 51, 51)
                .addComponent(fou, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equ)
                    .addComponent(fou)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(time)
                        .addComponent(date))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
SuivieTun ac =new SuivieTun();
        ac.setVisible(true);
        this.hide();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int a;DefaultTableModel modelo;
int x=ho.getSelectedIndex();
a=x;
connection con = null ;
        String [] t2={"Hopital","Cas hospitalisé","Lits encore disponibles en réa"};
       
            String [] t=new String[3];
            modelo =new DefaultTableModel(null,t2); 
            
    try {
        con = new connection();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
    }
            Statement cmd = null;
    try {
        cmd = con.c.createStatement();
    } catch (SQLException ex) {
        Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
    }
             ResultSet res = null;
            
    try {
        if(a==0) {equ.setEnabled(false);
        fou.setEnabled(false);
        jButton5.setEnabled(false);
        res = cmd.executeQuery("SELECT hop,cashosp,nblits FROM hopitaux");}
        else { equ.setEnabled(true);
        fou.setEnabled(true);
        jButton5.setEnabled(true);
                res = cmd.executeQuery("SELECT hop,cashosp,nblits FROM hopitaux where idH='"+a+"';");}
    } catch (SQLException ex) {
        Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        while(res.next()){ t[0]= res.getString("hop");
        t[1]= res.getString("cashosp");
        t[2]= res.getString("nblits");
        modelo.addRow(t);}
    } catch (SQLException ex) {
        Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
    }
             th.setModel(modelo);




            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void equActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equActionPerformed

        DefaultTableModel modelo;
int x=ho.getSelectedIndex();
connection con = null ; 

String [] t2={"Nom equipement","nombre"};
       
            String [] t=new String[2];
            modelo =new DefaultTableModel(null,t2);
        try {
            con = new connection();
// TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
        }
        Statement cmd = null;
        try {
            cmd = con.c.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
        }
         ResultSet res = null;
        try {
            res = cmd.executeQuery("SELECT nomequi,nbequi FROM equipement WHERE idhop='"+x+"';");
        } catch (SQLException ex) {
            Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
        }
        
String ch="";
        try {
            while(res.next()){ t[0]= res.getString("nomequi");
            t[1]= res.getString("nbequi");
             ch=ch+'\n'+t[0]+"  :  "+t[1];
            modelo.addRow(t);}
        } catch (SQLException ex) {
            Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        javax.swing.JOptionPane.showMessageDialog(null,ch,"équipements manquantes",1);
/*javax.swing.JOptionPane.showMessageDialog(null,ch);*/
    }//GEN-LAST:event_equActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
DefaultTableModel modelo;
int x=ho.getSelectedIndex();
connection con = null ; 

String [] t2={"type don","valeur"};
       
            String [] t=new String[2];
            modelo =new DefaultTableModel(null,t2);
        try {
            con = new connection();
// TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
        }
        Statement cmd = null;
        try {
            cmd = con.c.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
        }
int y=0;         ResultSet res = null;
        try {
            res = cmd.executeQuery("SELECT type,valeur FROM dons WHERE idhop='"+x+"' and done='"+y+"';");
        } catch (SQLException ex) {
            Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
        }
        
String ch="";
        try {
            while(res.next()){ t[0]= res.getString("type");
            t[1]= res.getString("valeur");
             ch=ch+'\n'+t[0]+"  :  "+t[1];
            modelo.addRow(t);}
        } catch (SQLException ex) {
            Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
        }
        
 javax.swing.JOptionPane.showMessageDialog(null,ch,"Appels à dons",1);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void fouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fouActionPerformed
DefaultTableModel modelo;
int x=ho.getSelectedIndex();
connection con = null ; 

String [] t2={"Nom fourn","quantité"};
       
            String [] t=new String[2];
            modelo =new DefaultTableModel(null,t2);
        try {
            con = new connection();
// TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
        }
        Statement cmd = null;
        try {
            cmd = con.c.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
        }
         ResultSet res = null;
         int y=0;
        try {
            res = cmd.executeQuery("SELECT nomf,quantité FROM fournitures WHERE idhop='"+x+"' and done='"+y+"';");
        } catch (SQLException ex) {
            Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
        }
        
String ch="";
        try {
            while(res.next()){ t[0]= res.getString("nomf");
            t[1]= res.getString("quantité");
             ch=ch+'\n'+t[0]+"  :  "+t[1];
            modelo.addRow(t);}
        } catch (SQLException ex) {
            Logger.getLogger(hopital.class.getName()).log(Level.SEVERE, null, ex);
        }
        
 javax.swing.JOptionPane.showMessageDialog(null,ch,"Demande fournitures",1);
           // TODO add your handling code here:
    }//GEN-LAST:event_fouActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hopital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hopital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hopital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hopital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hopital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JButton equ;
    private javax.swing.JButton fou;
    private javax.swing.JComboBox ho;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable th;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
